targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: testbor|lib/schema.graphql
          type_overrides:
            BigInteger:
              name: int
            BigDecimal:
              name: double
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: testbor|lib/schema.graphql

